### ISSUE TITLE
JobID

### ISSUE THREAD

**Issue by cacothi** [gabebear/TSPPrintingExample#1]
Hi Gabe,

This  is not an issue, but  I saw  your post on stackoverflow regards to the Star  Micronics printer. I have made  the integration with  Epson, and on their  onReceive method it's possible to retrieve a JobID related  to (set on send to print).

I couldn't find anything relate  to it and not many posts  around there.  Did  you manage to set the JobID and  retrieve it on Receive ?

**Comment by gabebear** [comment]
I haven't tried using the Epson thermal printers, the Star printers this was made for don't really have any concept of a "job". Honestly, I'd be surprised if this project compiles without some fixes/tweaks since it's been 6years since I updated it.
